#!/usr/bin/env bash

selected=$(find ~/ ~/TEC ~/dotjrr -mindepth 1 -maxdepth 3 -type d | fzf)
if [[ -z "$selected" ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr ":., " "____")

switch_to() {
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t "$selected_name"
    tmux select-window -t "$selected_name:scratch"
  else
    tmux switch-client -t "$selected_name"
    tmux select-window -t "$selected_name:scratch"
  fi
}

if tmux has-session -t="$selected_name" 2>/dev/null; then
  switch_to
  exit 0
fi

# 1. Crear la sesión con zsh para que no muera instantáneamente
tmux new-session -d -s "$selected_name" -n yazi -c "$selected" "zsh"

# 2. Esperar un toque y luego enviar el comando de yazi
tmux send-keys -t "$selected_name:1" "yazi" C-m

# 3. Crear ventana vacía scratch
tmux new-window -t "$selected_name" -n scratch -c "$selected"

# 4. Crear ventana de Opencode
tmux new-window -t "$selected_name" -n opencode -c "$selected" '/home/javialroro/.opencode/bin/opencode .'

switch_to
